<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="38" started-at="2017-09-13T07:32:05Z" finished-at="2017-09-13T07:32:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="38" started-at="2017-09-13T07:32:05Z" finished-at="2017-09-13T07:32:05Z">
      <class name="com.test.framework.utils.MockDemo">
        <test-method status="FAIL" signature="test()[pri:0, instance:com.test.framework.utils.MockDemo@50f8360d]" name="test" duration-ms="26" started-at="2017-09-13T15:32:05Z" finished-at="2017-09-13T15:32:05Z">
          <exception class="org.powermock.api.mockito.ClassNotPreparedException">
            <message>
              <![CDATA[
The class com.test.framework.utils.HttpUtil not prepared for test.
To prepare this class, add class to the '@PrepareForTest' annotation.
In case if you don't use this annotation, add the annotation on class or  method level. 
]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.powermock.api.mockito.ClassNotPreparedException: 
The class com.test.framework.utils.HttpUtil not prepared for test.
To prepare this class, add class to the '@PrepareForTest' annotation.
In case if you don't use this annotation, add the annotation on class or  method level. 

	at org.powermock.api.mockito.expectation.reporter.MockitoPowerMockReporter.classNotPrepared(MockitoPowerMockReporter.java:31)
	at org.powermock.api.mockito.internal.mockcreation.MockTypeValidatorFactory$DefaultMockTypeValidator.validate(MockTypeValidatorFactory.java:38)
	at org.powermock.api.mockito.internal.mockcreation.AbstractMockCreator.validateType(AbstractMockCreator.java:18)
	at org.powermock.api.mockito.internal.mockcreation.MockCreator.createMock(MockCreator.java:57)
	at org.powermock.api.mockito.internal.mockcreation.MockCreator.mock(MockCreator.java:47)
	at org.powermock.api.mockito.PowerMockito.mockStatic(PowerMockito.java:71)
	at com.test.framework.utils.MockDemo.test(MockDemo.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:330)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.powermock.api.mockito.ClassNotPreparedException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- com.test.framework.utils.MockDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
