<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="yangxiaobin" name="cn.test.framework.tests.InterfaceTest" tests="2" failures="2" timestamp="14 Sep 2017 07:38:04 GMT" time="2.585" errors="0">
  <testcase name="test_image_rec" time="1.439" classname="cn.test.framework.tests.InterfaceTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : address error expected: 北京市崇文区安化北里1号长保大厦123 actual: 北京市崇文区安化北里1号笋保大厦 expected [2] but found [1] in method : .test_image_rec(InterfaceTest:67)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:67)
	at message : issue_date error expected: 2008-07-10 actual: null expected [2] but found [1] in method : .test_image_rec(InterfaceTest:81)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:81)
]]>
    </failure>
  </testcase> <!-- test_image_rec -->
  <testcase name="test_image_rec" time="1.146" classname="cn.test.framework.tests.InterfaceTest">
    <failure type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable
	at message : address error expected: 北京市崇文区安化北里1号长保大厦 actual: 北京市崇文区安化北里1号笋保大厦 expected [2] but found [1] in method : .test_image_rec(InterfaceTest:67)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:67)
	at message : issue_date error expected: 2008-07-10 actual: null expected [2] but found [1] in method : .test_image_rec(InterfaceTest:81)
	at cn.test.framework.tests.InterfaceTest.test_image_rec(InterfaceTest.java:81)
]]>
    </failure>
  </testcase> <!-- test_image_rec -->
</testsuite> <!-- cn.test.framework.tests.InterfaceTest -->
